apiVersion: v1
kind: Service
metadata:
  name: app-api
  labels:
    app: app-api
spec: 
  ports:
    - name: "5152"
      port: 5152
      targetPort: 5152
      protocol: TCP
  selector:
    app: app-api