apiVersion: v1
kind: Service
metadata:
  name: app-api
  labels:
    app: app-api
spec: 
  ports:
    - name: "5153"
      port: 5153
      targetPort: 515
      protocol: TCP
  selector:
    app.kubernetes.io/name: app-api